// DEYOTLAN: pointer-based reordering for the curated navigation.
/**
 * Drag-to-reorder for the wiki nav, admin only.
 *
 * ## Why Pointer Events rather than HTML5 drag and drop
 *
 * Decisive: HTML5 `dragstart`/`drop` are **not generated by touch on iOS Safari at
 * all**, and are unreliable on Android Chrome. The primary use case for this nav is a
 * phone at the games table, so HTML5 DnD would simply not work where it matters most.
 *
 * Supporting reasons: `dataTransfer` cannot carry live objects, the OS drag image is
 * unstylable and would look nothing like the liquid-glass theme, and HTML5 DnD offers
 * no auto-scroll -- which a long sidebar on a six-inch screen needs.
 *
 * `setPointerCapture` gives one code path for mouse, touch and pen, keeps events
 * flowing to the origin element once the finger leaves it, and leaves the drag ghost
 * entirely under our control.
 *
 * ## Interaction rules
 *
 * - `touch-action: none` is set on the **grip only**, so the list still scrolls
 *   normally when the user drags anywhere else.
 * - A long press (350 ms, under 10 px of movement) on a row is a secondary gesture,
 *   cancelled by scrolling.
 * - Hovering a collapsed group for 600 ms expands it (spring-loaded folders).
 * - Everything is operable from the keyboard: the grip is a real button.
 */

import type { RenderedGroup } from "./reconcile"

export interface DndHost {
  root: HTMLElement
  getModel(): RenderedGroup[]
  /** Commit a reordered model: repaint, then schedule persistence. */
  onReorder(model: RenderedGroup[]): void
  announce(message: string): void
}

const LONG_PRESS_MS = 350
const LONG_PRESS_SLOP_PX = 10
const SPRING_OPEN_MS = 600
const AUTOSCROLL_EDGE_PX = 48
const AUTOSCROLL_MAX_PX = 14

interface Position {
  groupIndex: number
  itemIndex: number
}

/** Move an item between positions, returning a new model. */
export function moveItem(model: RenderedGroup[], from: Position, to: Position): RenderedGroup[] {
  const next = model.map((g) => ({ ...g, items: [...g.items] }))
  const [moved] = next[from.groupIndex].items.splice(from.itemIndex, 1)
  if (!moved) return model

  let targetIndex = to.itemIndex
  // Removing from an earlier slot in the same group shifts everything after it.
  if (from.groupIndex === to.groupIndex && from.itemIndex < to.itemIndex) targetIndex--

  const clamped = Math.max(0, Math.min(targetIndex, next[to.groupIndex].items.length))
  next[to.groupIndex].items.splice(clamped, 0, moved)
  return next
}

export function attachDnd(host: DndHost) {
  const { root } = host
  root.classList.add("is-admin")

  const list = root.querySelector<HTMLElement>(".explorer-ul")
  if (!list) return () => {}

  const cleanups: Array<() => void> = []
  const on = (el: EventTarget, ev: string, fn: any, opts?: AddEventListenerOptions) => {
    el.addEventListener(ev, fn, opts)
    cleanups.push(() => el.removeEventListener(ev, fn, opts))
  }

  // --- indices -------------------------------------------------------------

  const positionOf = (li: HTMLElement): Position | null => {
    const inner = li.parentElement // ul.content
    const groupLi = inner?.closest("li")
    if (!inner || !groupLi) return null
    const groupLis = [...list.children].filter(
      (c) => c.tagName === "LI" && c !== groupLi.parentElement,
    )
    const groupIndex = groupLis.indexOf(groupLi)
    const itemIndex = [...inner.children].indexOf(li)
    if (groupIndex < 0 || itemIndex < 0) return null
    return { groupIndex, itemIndex }
  }

  // --- drag state ----------------------------------------------------------

  let dragging: {
    li: HTMLElement
    from: Position
    ghost: HTMLElement
    indicator: HTMLElement
    offsetY: number
    target: Position | null
    pointerId: number
    grip: HTMLElement
  } | null = null

  let springTimer: number | undefined
  let autoScrollFrame: number | undefined

  const makeGhost = (li: HTMLElement): HTMLElement => {
    const rect = li.getBoundingClientRect()
    const ghost = li.cloneNode(true) as HTMLElement
    ghost.classList.add("drag-ghost")
    ghost.style.position = "fixed"
    ghost.style.left = `${rect.left}px`
    ghost.style.top = `${rect.top}px`
    ghost.style.width = `${rect.width}px`
    ghost.style.pointerEvents = "none"
    ghost.style.zIndex = "9999"
    document.body.appendChild(ghost)
    return ghost
  }

  const makeIndicator = (): HTMLElement => {
    const el = document.createElement("div")
    el.className = "drop-indicator"
    return el
  }

  const clearSpring = () => {
    if (springTimer !== undefined) {
      clearTimeout(springTimer)
      springTimer = undefined
    }
  }

  const stopAutoScroll = () => {
    if (autoScrollFrame !== undefined) {
      cancelAnimationFrame(autoScrollFrame)
      autoScrollFrame = undefined
    }
  }

  const autoScroll = (clientY: number) => {
    const rect = list.getBoundingClientRect()
    let delta = 0
    if (clientY < rect.top + AUTOSCROLL_EDGE_PX) {
      delta = -Math.ceil(
        ((rect.top + AUTOSCROLL_EDGE_PX - clientY) / AUTOSCROLL_EDGE_PX) * AUTOSCROLL_MAX_PX,
      )
    } else if (clientY > rect.bottom - AUTOSCROLL_EDGE_PX) {
      delta = Math.ceil(
        ((clientY - (rect.bottom - AUTOSCROLL_EDGE_PX)) / AUTOSCROLL_EDGE_PX) * AUTOSCROLL_MAX_PX,
      )
    }
    stopAutoScroll()
    if (delta === 0) return
    const step = () => {
      list.scrollTop += delta
      autoScrollFrame = requestAnimationFrame(step)
    }
    autoScrollFrame = requestAnimationFrame(step)
  }

  /** Work out where the pointer is asking to drop, and show the indicator there. */
  const updateTarget = (clientX: number, clientY: number) => {
    if (!dragging) return
    const under = document.elementFromPoint(clientX, clientY)
    if (!under) return

    // Over a collapsed group heading: spring it open rather than refusing the drop.
    const container = under.closest<HTMLElement>(".folder-container")
    if (container) {
      const outer = container.nextElementSibling
      if (outer instanceof HTMLElement && !outer.classList.contains("open")) {
        if (springTimer === undefined) {
          springTimer = window.setTimeout(() => {
            outer.classList.add("open")
            springTimer = undefined
          }, SPRING_OPEN_MS)
        }
      }
    } else {
      clearSpring()
    }

    const overLi = under.closest<HTMLElement>("li")
    if (!overLi || overLi === dragging.li) return

    // A leaf row: drop above or below it depending on which half we are over.
    if (overLi.querySelector(":scope > a")) {
      const pos = positionOf(overLi)
      if (!pos) return
      const rect = overLi.getBoundingClientRect()
      const below = clientY > rect.top + rect.height / 2
      overLi.parentElement?.insertBefore(dragging.indicator, below ? overLi.nextSibling : overLi)
      dragging.target = { groupIndex: pos.groupIndex, itemIndex: pos.itemIndex + (below ? 1 : 0) }
      return
    }

    // A group row: drop at the end of that group.
    const inner = overLi.querySelector<HTMLElement>("ul.content")
    const outer = overLi.querySelector<HTMLElement>(".folder-outer")
    if (inner && outer?.classList.contains("open")) {
      const groupLis = [...list.children].filter((c) => c.tagName === "LI")
      const groupIndex = groupLis.indexOf(overLi)
      if (groupIndex < 0) return
      inner.appendChild(dragging.indicator)
      dragging.target = { groupIndex, itemIndex: inner.children.length }
    }
  }

  const finish = (commit: boolean) => {
    if (!dragging) return
    const { li, ghost, indicator, from, target, grip, pointerId } = dragging
    dragging = null

    clearSpring()
    stopAutoScroll()
    ghost.remove()
    indicator.remove()
    li.classList.remove("is-dragging")
    root.classList.remove("is-dragging-active")
    try {
      grip.releasePointerCapture(pointerId)
    } catch {
      /* the pointer may already be gone */
    }

    if (!commit || !target) {
      host.announce("Move cancelled.")
      return
    }
    const model = host.getModel()
    const label = model[from.groupIndex]?.items[from.itemIndex]?.label ?? "Page"
    const next = moveItem(model, from, target)
    host.onReorder(next)
    host.announce(`${label} moved to ${next[target.groupIndex]?.label ?? "group"}.`)
  }

  const beginDrag = (li: HTMLElement, grip: HTMLElement, pointerId: number, clientY: number) => {
    const from = positionOf(li)
    if (!from) return
    const rect = li.getBoundingClientRect()
    dragging = {
      li,
      from,
      ghost: makeGhost(li),
      indicator: makeIndicator(),
      offsetY: clientY - rect.top,
      target: null,
      pointerId,
      grip,
    }
    li.classList.add("is-dragging")
    root.classList.add("is-dragging-active")
    try {
      grip.setPointerCapture(pointerId)
    } catch {
      /* capture is an optimisation, not a requirement */
    }
    navigator.vibrate?.(8)
    host.announce("Picked up. Drag to reorder.")
  }

  // --- pointer wiring ------------------------------------------------------

  const wireGrip = (grip: HTMLElement) => {
    const li = grip.closest<HTMLElement>("li")
    if (!li) return

    on(grip, "pointerdown", (e: PointerEvent) => {
      if (e.button !== 0 && e.pointerType === "mouse") return
      e.preventDefault()
      e.stopPropagation()
      beginDrag(li, grip, e.pointerId, e.clientY)
    })

    on(grip, "pointermove", (e: PointerEvent) => {
      if (!dragging || dragging.pointerId !== e.pointerId) return
      e.preventDefault()
      dragging.ghost.style.top = `${e.clientY - dragging.offsetY}px`
      updateTarget(e.clientX, e.clientY)
      autoScroll(e.clientY)
    })

    on(grip, "pointerup", (e: PointerEvent) => {
      if (!dragging || dragging.pointerId !== e.pointerId) return
      e.preventDefault()
      finish(true)
    })

    on(grip, "pointercancel", () => finish(false))

    // --- keyboard ---
    // The only way this is operable without a pointer, and cheap to provide.
    on(grip, "keydown", (e: KeyboardEvent) => {
      const model = host.getModel()
      const from = positionOf(li)
      if (!from) return

      if (e.key === " " || e.key === "Enter") {
        e.preventDefault()
        const picked = grip.getAttribute("aria-pressed") === "true"
        grip.setAttribute("aria-pressed", picked ? "false" : "true")
        li.classList.toggle("is-keyboard-dragging", !picked)
        host.announce(picked ? "Dropped." : "Picked up. Use the arrow keys to move it.")
        return
      }
      if (grip.getAttribute("aria-pressed") !== "true") return

      if (e.key === "Escape") {
        e.preventDefault()
        grip.setAttribute("aria-pressed", "false")
        li.classList.remove("is-keyboard-dragging")
        host.announce("Move cancelled.")
        return
      }

      const dir = e.key === "ArrowUp" ? -1 : e.key === "ArrowDown" ? 1 : 0
      if (dir === 0) return
      e.preventDefault()

      let to: Position
      const group = model[from.groupIndex]
      const nextIndex = from.itemIndex + dir
      if (nextIndex < 0) {
        // Off the top: move to the end of the previous group.
        const g = from.groupIndex - 1
        if (g < 0) return
        to = { groupIndex: g, itemIndex: model[g].items.length }
      } else if (nextIndex > group.items.length - 1) {
        const g = from.groupIndex + 1
        if (g > model.length - 1) return
        to = { groupIndex: g, itemIndex: 0 }
      } else {
        to = { groupIndex: from.groupIndex, itemIndex: nextIndex }
      }

      const label = group.items[from.itemIndex]?.label ?? "Page"
      const next = moveItem(model, from, to)
      host.onReorder(next)
      host.announce(
        `${label} moved to position ${to.itemIndex + 1} of ${next[to.groupIndex].label}.`,
      )
    })
  }

  // --- long press anywhere on a row (secondary gesture) --------------------

  let pressTimer: number | undefined
  let pressStart: { x: number; y: number; li: HTMLElement; grip: HTMLElement; id: number } | null =
    null

  const cancelPress = () => {
    if (pressTimer !== undefined) clearTimeout(pressTimer)
    pressTimer = undefined
    pressStart = null
  }

  on(list, "pointerdown", (e: PointerEvent) => {
    const li = (e.target as HTMLElement)?.closest<HTMLElement>("li")
    if (!li || !li.querySelector(":scope > a")) return
    const grip = li.querySelector<HTMLElement>(".drag-grip")
    if (!grip || grip.contains(e.target as Node)) return
    pressStart = { x: e.clientX, y: e.clientY, li, grip, id: e.pointerId }
    pressTimer = window.setTimeout(() => {
      if (!pressStart) return
      beginDrag(pressStart.li, pressStart.grip, pressStart.id, pressStart.y)
      pressStart = null
    }, LONG_PRESS_MS)
  })

  on(list, "pointermove", (e: PointerEvent) => {
    if (pressStart) {
      const moved = Math.hypot(e.clientX - pressStart.x, e.clientY - pressStart.y)
      if (moved > LONG_PRESS_SLOP_PX) cancelPress()
    }
    if (!dragging || dragging.pointerId !== e.pointerId) return
    dragging.ghost.style.top = `${e.clientY - dragging.offsetY}px`
    updateTarget(e.clientX, e.clientY)
    autoScroll(e.clientY)
  })

  on(list, "pointerup", (e: PointerEvent) => {
    cancelPress()
    if (dragging && dragging.pointerId === e.pointerId) finish(true)
  })
  on(list, "scroll", cancelPress, { passive: true })
  on(window, "keydown", (e: KeyboardEvent) => {
    if (e.key === "Escape" && dragging) finish(false)
  })

  // --- grips ---------------------------------------------------------------

  for (const li of list.querySelectorAll<HTMLElement>("li")) {
    const link = li.querySelector(":scope > a")
    if (!link) continue

    const grip = document.createElement("button")
    grip.type = "button"
    grip.className = "drag-grip"
    grip.setAttribute("aria-pressed", "false")
    grip.setAttribute("aria-label", `Reorder ${link.textContent ?? "page"}`)
    grip.innerHTML = '<span aria-hidden="true">⠿</span>'
    li.insertBefore(grip, link)
    wireGrip(grip)
  }

  return () => {
    cleanups.forEach((fn) => fn())
    clearSpring()
    stopAutoScroll()
  }
}
